AjaxLab/Controllers/HomeController.cs
using AjaxLab.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AjaxLab.Controllers
{
    public class HomeController : Controller
    {
        private NorthwindEntities ctx = new NorthwindEntities();

        public ActionResult Index()
        {

            NorthwindEntities ctx = new NorthwindEntities();

            var cC = ctx.Categories.OrderBy(c => c.CategoryID).ToList();
            cC.Insert(0, new Category { CategoryID = 0 });

            var cdrop = new SelectList(cC
               ,
              "CategoryID", "CategoryName");


            ViewBag.Categories = cdrop;

            var sC = ctx.Suppliers.OrderBy(c => c.SupplierID).ToList();
            sC.Insert(0, new Supplier { SupplierID = 0 });



            ViewBag.Suppliers = new SelectList(
               sC,
              "SupplierID", "CompanyName");

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AjaxLab/Controllers/ProductController.cs
using AjaxLab.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AjaxLab.Controllers
{
    public class ProductController : Controller
    {
        NorthwindEntities ctx = new NorthwindEntities();

        // GET: Product
        public ActionResult Index()
        {
            return View();
        }



        public PartialViewResult ProductSearch(int Categories, int Suppliers)
        {

            IEnumerable<Product> pros;
            var s = "";
            if (Categories == 0 && Suppliers == 0)
            {
                pros  = ctx.Products.ToList();

                s = "display all products";


            } else if(Categories == 0)
            {
                pros = ctx.Products.Where(p=> p.SupplierID == Suppliers).ToList();
                s = "display products that belong to the " + ctx.Suppliers.Find(Suppliers).CompanyName +"supplier.";


            } else if(Suppliers == 0)
            {
                pros = ctx.Products.Where(p => p.CategoryID == Categories).ToList();
                s = "display products that belong to the " + ctx.Categories.Find(Categories).CategoryName + "category.";
            }
            else
            {
                pros = ctx.Products
                .Where(p => p.CategoryID == Categories)
                .Where(p => p.SupplierID == Suppliers)
                .ToList();
                s = "display products that belong to " + ctx.Categories.Find(Categories).CategoryName 
                    + " category from "
                    + ctx.Suppliers.Find(Suppliers).CompanyName
                    + " supplier";
            }


            List<Object> o = new List<Object>() { pros, s };
            return PartialView("_ProductPartial", o);

            //IEnumerable<Product> pros = ctx.Products
            //    .Include("Category")
            //    .Include("Supplier").Where(p =>p.CategoryID == Categories)
            //    .Where(p => p.SupplierID== Suppliers)
            //    .ToList();

            //return PartialView("_ProductPartial", pros);
            

        }
    }
}

AjaxLab/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AjaxLab/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AjaxLab/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@section scripts {

    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/ProductJavaScript.js")" type="text/javascript"></script>
    
}


<div>
    <br /><br />

@using (Ajax.BeginForm("ProductSearch", "Product",
                new AjaxOptions
                {
                    InsertionMode = InsertionMode.Replace,
                    HttpMethod = "GET",
                    OnFailure = "searchFailed",
                    LoadingElementId = "ajax-loader",
                    UpdateTargetId = "searchresults",
                }))
{

    @Html.DropDownList("Categories", ViewBag.Categories as SelectList)

    @Html.DropDownList("Suppliers", ViewBag.Suppliers as SelectList)
    <input type="submit" value="search" />
    <img id="ajax-loader"
         src="@Url.Content("~/Content/Images/ajax-loader.gif")"
         style="display:none" />
}

    <div id="searchresults"></div>

</div>